# Generated by Django 5.0.3 on 2024-04-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Caption')),
                ('preview', models.CharField(max_length=250, verbose_name='Preview')),
                ('full_text', models.TextField(verbose_name='Article')),
                ('date', models.DateField(verbose_name='Posting date')),
            ],
        ),
    ]
