# Generated by Django 5.0.3 on 2024-04-17 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='articles',
            name='time',
            field=models.TimeField(default=datetime.time(16, 0), verbose_name='Posting time'),
        ),
    ]
